name: SkyblockPlugin
author: Dan Beneventano
version: 0.1.0
main: me.danbeneventano.skyblockplugin.SkyblockPlugin

commands:
  island:
    description: Access island information or settings
    usage: /island
    aliases: [is]
  chat:
    description: Change chat settings
    usage: /chat
    aliases: [ch, channel]
  challenges:
    description: View challenges
    usage: /challenges
    aliases: [c, challenges]